[package]
name = "circomspect"
version = "0.4.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "3.2", features = ["derive"] }
log = "0.4"
parser = { path = "../parser" }
pretty_env_logger = "0.4"
program_analysis = { path = "../program_analysis" }
program_structure = { path = "../program_structure" }
serde_json = "1.0.81"
